

export const Socials = [
  {
    name: "Facebook",
    src: "/facebook.svg",
  },
  {
    name: "Instagram",
    src: "/discord.svg",
  },
];

export const Frontend_skill = [
  {
    skill_name: "Html 5",
    Image: "/html.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Css",
    Image: "/css.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Java Script",
    Image: "/js.png",
    width: 50,
    height: 50,
  },
  {
    skill_name: "React",
    Image: "/react.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Type Script",
    Image: "/ts.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Tailwind Css",
    Image: "/tailwind.png",
    width: 80,
    height: 80,
  },
  
  {
    skill_name: "Next js 13",
    Image: "/next.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Material UI",
    Image: "/mui.png",
    width: 80,
    height: 80,
  },
];

export const Backend_skill = [
  {
    skill_name: "Mongo db",
    Image: "/mongodb.png",
    width: 40,
    height: 40,
  },
  {
    skill_name: "Express js",
    Image: "/express.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Node js",
    Image: "/node-js.png",
    width: 80,
    height: 80,
  },
];



export const Other_skill = [
  {
    skill_name: "Fire base",
    Image: "/Firebase.png",
    width: 55,
    height: 55,
  },
  {
    skill_name: "Stripe Payment",
    Image: "/stripe.webp",
    width: 80,
    height: 80,
  },
];
export const Testimonials = [
  {
    name: "Pramod Tharu",
    description: "Do not be a coder be programer with latest and popular tech",
    Image: "/prampod.jpg",
    width: 40,
    height: 40,
  },
  {
    name: "Sabin Chaudhary",
    Image: "/sabin.jpg",
    description: "Do not be a coder be programer with latest and popular tech",
    width: 40,
    height: 40,
  },
  {
    name: "Dindayal Chaudhary",
    Image: "/dinu.jpg",
    description: "Do not be a coder be programer with latest and popular tech",
    width: 40,
    height: 40,
  },
  {
    name: "Arun Neupane",
    Image: "/arun.jpg",
    description: "Do not be a coder be programer with latest and popular tech",
    width: 40,
    height: 40,
  },
  {
    name: "Amrit Tharu",
    Image: "/Amrit.jpg",
    description: "Do not be a coder be programer with latest and popular tech",
    width: 40,
    height: 40,
  },
  {
    name: "Sunil Tharu",
    Image: "/Sunil.jpg",
    description: "Do not be a coder be programer with latest and popular tech",
    width: 50,
    height: 50,
  },
];


export const sections = [
  { name: "Code", link: "/code" },
  { name: "Plan", link: "/plan" },
  { name: "Collaborate", link: "/collaborate" },
  { name: "Automate", link: "/automate" },
  { name: "Secure", link: "/secure" },
];


export const data = [
  "Apple",
  "Banana",
  "Cherry",
  "Date",
  "Elderberry",
  "Fig",
  "Grapes",
  "Honeydew",
  "Indian Fig",
  "Jackfruit",
  "Kiwi",
  "Lemon",
  "Mango",
  "Nectarine",
  "Olives",
  "Papaya",
  "Quince",
  "Raspberry",
  "Strawberry",
  "Tangerine",
  "Uva",
  "Watermelon",
  "Xigua",
  "Yam",
  "Zucchini",
  "Acai",
  "Blueberry",
  "Cantaloupe",
  "Dragonfruit",
  "Eggfruit",
  "Feijoa",
  "Galia Melon",
  "Hala Fruit",
  "Imbe",
  "Jambolan",
  "Kumquat",
  "Lime",
  "Mulberry",
  "Nance",
  "Orange",
  "Passionfruit",
  "Quandong",
  "Rambutan",
  "Starfruit",
  "Tomato",
  "Upland Cress",
  "Velvet Apple",
  "White Currant",
  "Xoconostle",
  "Yellow Passionfruit",
  "Zinfandel",
  "Apricot",
  "Blackberry",
  "Coconut",
  "Durian",
  "Elderflower",
  "Fuyu Persimmon",
  "Guava",
  "Honeycrisp Apple",
  "Imbu",
  "Jujube",
  "Kaffir Lime",
  "Litchi",
  "Mamey",
  "Noni",
  "Olallieberry",
  "Pawpaw",
  "Quenepa",
  "Raisin",
  "Sugar Apple",
  "Tamarind",
  "Urtle",
  "Vimto",
  "Wampee",
  "Xanadu",
  "Yellow Sapote",
  "Zara",
  "Atemoya",
  "Bittermelon",
  "Camu Camu",
  "Duku",
  "Emu Apple",
  "Finger Lime",
  "Goji Berry",
  "Horned Melon",
  "Indian Gooseberry",
  "Jamaican Tangelo",
  "Kaffir Plum",
  "Langsat",
  "Medlar",
  "Nipa Palm",
  "Olive",
  "Pineapple",
  "Queen's Crown",
  "Red Currant",
  "Soursop",
  "Tamarillo",
  "Uva Ursi",
  "Volkamer Lemon",
  "Witch Hazel",
  "Xanadu Fruit",
  "Yellow Dragonfruit",
  "Zamboni Fruit",
];
